apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-worker
  labels:
    app: langfuse-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse-worker
  template:
    metadata:
      labels:
        app: langfuse-worker
    spec:
      containers:
        - name: langfuse-worker
          image: langfuse/langfuse-worker:3
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: langfuse-secret
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
